In [17]:
import numpy as np

# Create an array of zeros

arr = np.zeros((5,5), dtype=int)

print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [18]:
# Set the edges of the array to ones

arr[0]=1
arr[-1]=1
arr[:,0]=1
arr[:,-1]=1

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [20]:
# Set the center element to 9

arr[2,2] = 9

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
